"use client";

import { useEffect, useMemo, useState } from "react";
import { formatCurrency, normalizeText } from "@/lib/format";
import { readStorage, storageKeys } from "@/lib/storage";
import type { Order, OrderStatus } from "@/types";

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | OrderStatus>("all");
  useEffect(() => setOrders(readStorage<Order[]>(storageKeys.orders, [])), []);
  const visible = useMemo(() => orders.slice().reverse().filter((order) => normalizeText(`${order.code} ${order.customer.fullName} ${order.customer.phone}`).includes(normalizeText(query)) && (status === "all" || (order.status || "Đã ghi nhận") === status)), [orders, query, status]);
  return <div className="admin-content admin-content--wide"><div className="admin-heading"><div><p className="eyebrow">Dữ liệu đặt hàng</p><h1>Quản lý đơn hàng</h1></div><label className="admin-status-filter">Trạng thái <select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="all">Tất cả</option><option>Đã ghi nhận</option><option>Đang xử lý</option><option>Đã giao</option><option>Đã hủy</option></select></label></div><label className="admin-search" style={{marginTop:18}}><input value={query} onChange={(e) => setQuery(e.target.value)} type="search" placeholder="Tìm mã đơn, khách hàng..." /></label><section className="admin-orders admin-orders--page"><div className="admin-section-heading"><div><h2>Danh sách đơn hàng</h2><p><strong>{visible.length}</strong> đơn được tìm thấy.</p></div></div><div className="admin-table-wrap"><table className="admin-orders-table"><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Liên hệ</th><th>Ngày đặt</th><th>Số món</th><th>Tổng tiền</th><th>Trạng thái</th></tr></thead><tbody>{visible.map((order) => <tr key={order.code}><td><strong>#{order.code}</strong></td><td>{order.customer.fullName}</td><td><span className="admin-contact-cell">{order.customer.phone}<small>{order.customer.email}</small></span></td><td>{new Intl.DateTimeFormat("vi-VN").format(new Date(order.createdAt))}</td><td>{order.items.reduce((sum,item) => sum + item.quantity,0)} món</td><td><strong>{formatCurrency(order.total)}</strong></td><td><select className="admin-order-state" value={order.status || "Đã ghi nhận"} onChange={(e) => setOrders((current) => current.map((item) => item.code === order.code ? {...item,status:e.target.value as OrderStatus} : item))}><option>Đã ghi nhận</option><option>Đang xử lý</option><option>Đã giao</option><option>Đã hủy</option></select></td></tr>)}</tbody></table>{!visible.length && <div className="admin-empty-orders">Chưa có đơn hàng phù hợp.</div>}</div></section></div>;
}
