-- Kho dữ liệu Mộc Nhiên dành cho Supabase (PostgreSQL)
-- Có thể chạy lại: danh mục và sản phẩm được cập nhật theo khóa chính, không bị chèn trùng.

begin;

-- 1. Danh mục
create table if not exists public.categories (
  id text primary key,
  name text not null,
  display_order integer not null default 0 check (display_order >= 0),
  created_at timestamptz not null default now()
);

-- 2. Sản phẩm
create table if not exists public.products (
  id text primary key,
  slug text not null unique,
  name text not null,
  category_id text not null references public.categories(id)
    on update cascade on delete restrict,
  price bigint not null check (price >= 0),
  compare_at_price bigint check (compare_at_price is null or compare_at_price >= price),
  stock integer not null default 0 check (stock >= 0),
  image text not null,
  images text[] not null default '{}'::text[],
  description text not null default '',
  featured boolean not null default false,
  is_new boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3. Đơn hàng
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  shipping_address text not null,
  note text,
  payment_method text not null default 'cod'
    check (payment_method in ('cod')),
  subtotal bigint not null default 0 check (subtotal >= 0),
  shipping_fee bigint not null default 0 check (shipping_fee >= 0),
  total bigint not null default 0 check (total >= 0),
  status text not null default 'Đã ghi nhận'
    check (status in ('Đã ghi nhận', 'Đang xử lý', 'Đã giao', 'Đã hủy')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Chi tiết đơn hàng: lưu tên, giá và ảnh tại thời điểm khách đặt.
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text references public.products(id) on update cascade on delete set null,
  product_name text not null,
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  product_image text,
  created_at timestamptz not null default now()
);

create index if not exists products_category_id_idx
  on public.products(category_id);
create index if not exists products_featured_idx
  on public.products(featured) where featured = true;
create index if not exists orders_created_at_idx
  on public.orders(created_at desc);
create index if not exists orders_status_idx
  on public.orders(status);
create index if not exists order_items_order_id_idx
  on public.order_items(order_id);

-- Tự cập nhật updated_at khi sửa sản phẩm hoặc đơn hàng.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- 4 danh mục thật trong ứng dụng. "Tất cả" chỉ là nút lọc nên không lưu thành danh mục.
insert into public.categories (id, name, display_order)
values
  ('gom', 'Gốm thủ công', 1),
  ('may-dan', 'Mây đan', 2),
  ('go', 'Đồ gỗ', 3),
  ('trang-tri', 'Trang trí', 4)
on conflict (id) do update set
  name = excluded.name,
  display_order = excluded.display_order;

-- Toàn bộ 8 sản phẩm hiện có trong data/products.ts.
insert into public.products (
  id, slug, name, category_id, price, compare_at_price, stock,
  image, images, description, featured, is_new
)
values
  (
    'macrame',
    'tranh-macrame-an-nhien',
    'Tranh Macramé An Nhiên',
    'trang-tri',
    390000,
    null,
    14,
    '/assets/images/products/do-thu-cong/tranh-treo-macrame.webp',
    array[
      '/assets/images/products/do-thu-cong/tranh-treo-macrame.webp',
      '/assets/images/products/San_pham/tranh-treo-macrame-original.webp'
    ]::text[],
    'Tranh macramé thắt tay từ sợi cotton, mang nét mềm mại và tự nhiên cho không gian sống.',
    true,
    true
  ),
  (
    'basket',
    'gio-may-dan-moc',
    'Giỏ Mây Đan Mộc',
    'may-dan',
    290000,
    null,
    21,
    '/assets/images/products/do-thu-cong/gio-may-dan.webp',
    array[
      '/assets/images/products/do-thu-cong/gio-may-dan.webp',
      '/assets/images/products/San_pham/gio-may-dan-original.webp'
    ]::text[],
    'Giỏ mây đan thủ công, gọn nhẹ và phù hợp để lưu trữ những vật dụng nhỏ trong nhà.',
    true,
    false
  ),
  (
    'wooden-tray',
    'khay-go-van-tu-nhien',
    'Khay Gỗ Vân Tự Nhiên',
    'go',
    320000,
    355000,
    8,
    '/assets/images/products/do-thu-cong/khay-go-trang-tri.webp',
    array[
      '/assets/images/products/do-thu-cong/khay-go-trang-tri.webp',
      '/assets/images/products/do-thu-cong/khay-go-hoa-van.webp'
    ]::text[],
    'Khay gỗ hoàn thiện thủ công, giữ nguyên đường vân ấm áp và vẻ đẹp mộc mạc của vật liệu.',
    true,
    false
  ),
  (
    'vase-set',
    'bo-binh-gom-moc-sac',
    'Bộ Bình Gốm Mộc Sắc',
    'gom',
    590000,
    720000,
    16,
    '/assets/images/products/do-my-nghe/bo-binh-gom-minimal.webp',
    array[
      '/assets/images/products/do-my-nghe/bo-binh-gom-minimal.webp',
      '/assets/images/products/San_pham/bo-binh-gom-minimal-original.webp',
      '/assets/images/products/do-my-nghe/binh-gom-trang-tri.webp'
    ]::text[],
    'Bộ bình gốm tạo hình và hoàn thiện thủ công, phối các sắc độ tự nhiên cho bàn trà hoặc kệ sách.',
    true,
    true
  ),
  (
    'bamboo-lamp',
    'den-tre-binh-minh',
    'Đèn Tre Bình Minh',
    'may-dan',
    690000,
    null,
    6,
    '/assets/images/products/do-my-nghe/den-tre-thu-cong.webp',
    array[
      '/assets/images/products/do-my-nghe/den-tre-thu-cong.webp',
      '/assets/images/products/San_pham/den-tre-thu-cong-original.webp'
    ]::text[],
    'Đèn tre đan tạo ánh sáng dịu, mang bầu không khí ấm cúng vào phòng khách và phòng ngủ.',
    true,
    false
  ),
  (
    'decor-vase',
    'binh-gom-vet-nang',
    'Bình Gốm Vệt Nắng',
    'gom',
    450000,
    null,
    12,
    '/assets/images/products/do-my-nghe/binh-gom-trang-tri.webp',
    array[
      '/assets/images/products/do-my-nghe/binh-gom-trang-tri.webp',
      '/assets/images/products/San_pham/binh-gom-trang-tri-original.webp'
    ]::text[],
    'Bình gốm trang trí với màu men nhẹ và bề mặt giàu cảm giác thủ công.',
    true,
    false
  ),
  (
    'wooden-shelf',
    'ke-go-da-nang',
    'Kệ Gỗ Đa Năng',
    'go',
    1290000,
    null,
    0,
    '/assets/images/products/noi-that-gia-dung/ke-go-trang-tri.webp',
    array[
      '/assets/images/products/noi-that-gia-dung/ke-go-trang-tri.webp',
      '/assets/images/products/San_pham/ke-go-trang-tri-original.webp'
    ]::text[],
    'Kệ gỗ nhiều tầng giúp sắp xếp sách và đồ trang trí gọn gàng.',
    false,
    false
  ),
  (
    'plant-pot',
    'chau-cay-de-ban',
    'Chậu Cây Để Bàn',
    'trang-tri',
    240000,
    null,
    0,
    '/assets/images/products/noi-that-gia-dung/chau-cay-de-ban.webp',
    array[
      '/assets/images/products/noi-that-gia-dung/chau-cay-de-ban.webp',
      '/assets/images/products/San_pham/chau-cay-de-ban-original.webp'
    ]::text[],
    'Chậu cây nhỏ dành cho bàn làm việc, kệ sách và những góc cần thêm sắc xanh.',
    false,
    false
  )
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  category_id = excluded.category_id,
  price = excluded.price,
  compare_at_price = excluded.compare_at_price,
  stock = excluded.stock,
  image = excluded.image,
  images = excluded.images,
  description = excluded.description,
  featured = excluded.featured,
  is_new = excluded.is_new;

-- Bảo vệ các bảng trong schema public.
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Khách chưa đăng nhập được xem danh mục và sản phẩm.
drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
on public.categories for select
to anon, authenticated
using (true);

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
to anon, authenticated
using (true);

-- Không mở quyền đọc/ghi đơn hàng cho trình duyệt ở bước này.
-- SQL Editor và service_role vẫn quản lý được; khi nối checkout sẽ thêm policy phù hợp.

commit;

-- Kiểm tra nhanh sau khi chạy: kết quả mong đợi là 4 danh mục và 8 sản phẩm.
select
  (select count(*) from public.categories) as category_count,
  (select count(*) from public.products) as product_count;
