"use client";

import { FormEvent, useMemo, useState } from "react";
import { products as sourceProducts } from "@/data/products";
import { formatCurrency, normalizeText } from "@/lib/format";
import type { Product } from "@/types";

export default function AdminProductsPage() {
  const [items, setItems] = useState<Product[]>(sourceProducts); const [query, setQuery] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [image, setImage] = useState(sourceProducts[0].image);
  const editing = items.find((item) => item.id === editingId); const visible = useMemo(() => items.filter((item) => normalizeText(`${item.name} ${item.categoryLabel}`).includes(normalizeText(query))), [items, query]);
  const edit = (product: Product) => { setEditingId(product.id); setImage(product.image); };
  const reset = () => { setEditingId(null); setImage(sourceProducts[0].image); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const category = String(data.get("category")) as Product["category"]; const product: Product = { id: editingId || `custom-${Date.now()}`, slug: editing?.slug || `san-pham-${Date.now()}`, name: String(data.get("name")), category, categoryLabel: ({gom:"Gốm thủ công","may-dan":"Mây đan",go:"Đồ gỗ","trang-tri":"Trang trí"} as const)[category], price: Number(data.get("price")), stock: Number(data.get("stock")), image, images: [image], description: String(data.get("description") || "") }; setItems((current) => editingId ? current.map((item) => item.id === editingId ? product : item) : [product, ...current]); setEditingId(product.id); };
  const upload = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setImage(String(reader.result)); reader.readAsDataURL(file); };
  return <div className="admin-content admin-content--wide"><div className="admin-heading"><div><p className="eyebrow">Danh mục cửa hàng</p><h1>Quản lý sản phẩm</h1></div><button className="admin-primary-button" type="button" onClick={reset}>Thêm sản phẩm</button></div><label className="admin-search" style={{marginTop:18}}><input value={query} onChange={(e) => setQuery(e.target.value)} type="search" placeholder="Tìm sản phẩm..." /></label><div className="admin-management-layout"><section className="admin-products-panel"><div className="admin-section-heading"><div><h2>Sản phẩm</h2><p><strong>{visible.length}</strong> sản phẩm trong danh sách.</p></div></div><div className="admin-table-wrap"><table className="admin-product-table"><thead><tr><th>#</th><th>Sản phẩm</th><th>Danh mục</th><th>Giá</th><th>Kho</th><th>Thao tác</th></tr></thead><tbody>{visible.map((product,index) => <tr key={product.id}><td>{index+1}</td><td><div className="admin-product-cell"><img src={product.image} alt="" /><strong>{product.name}</strong></div></td><td><span className="admin-category-tag">{product.categoryLabel}</span></td><td><strong>{formatCurrency(product.price)}</strong></td><td>{product.stock}</td><td><div className="admin-row-actions"><button type="button" onClick={() => edit(product)}>Sửa</button><button className="danger" type="button" onClick={() => setItems((current) => current.filter((item) => item.id !== product.id))}>Xóa</button></div></td></tr>)}</tbody></table></div></section><section className="admin-product-form-panel"><div className="admin-section-heading"><div><h2>{editing ? "Sửa sản phẩm" : "Thêm sản phẩm"}</h2><p>Thay đổi được cập nhật ngay trên bảng.</p></div></div><form key={editingId || "new"} className="admin-product-form" onSubmit={submit}><label><span>Tên sản phẩm</span><input name="name" defaultValue={editing?.name} required /></label><div className="admin-form-row"><label><span>Danh mục</span><select name="category" defaultValue={editing?.category || "gom"}><option value="gom">Gốm thủ công</option><option value="may-dan">Mây đan</option><option value="go">Đồ gỗ</option><option value="trang-tri">Trang trí</option></select></label><label><span>Giá bán</span><input name="price" type="number" defaultValue={editing?.price} min={1000} required /></label></div><label><span>Số lượng kho</span><input name="stock" type="number" defaultValue={editing?.stock ?? 10} min={0} required /></label><label><span>Ảnh sản phẩm</span><input type="file" accept="image/*" onChange={(e) => upload(e.target.files?.[0])} /></label><div className="admin-image-preview"><img src={image} alt="Ảnh xem trước" /></div><label><span>Mô tả</span><textarea name="description" defaultValue={editing?.description} rows={3} /></label><div className="admin-form-actions"><button className="admin-primary-button" type="submit">Lưu sản phẩm</button><button className="admin-secondary-button" type="button" onClick={reset}>Làm mới</button></div></form></section></div></div>;
}
